// auto-generated by bsg_ascii_to_rom.py from /home/paul/artix_7_test/bsg_fpga/vu37p_chip/bsg_tapeout_v1_tsmc40/toplevels/bsg_ac_black_parrot_quad_core_rc3/testing/traces/bsg_tag_boot.tr; do not modify
module bsg_tag_boot_rom #(parameter width_p=-1, addr_width_p=-1)
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
                                 // # PRO-TIP: Set editior syntax to bash (or sh)
                                 // ################################################################################
                                 // # DESIGN SPECIFIC TAG INFO
                                 // #
                                 // # Number | Description            | Width
                                 // # -------+------------------------+-------
                                 // #     0  | Clkgen Async Reset     | 1-bit
                                 // #   3-1  | Clkgen Oscillator      | 5-bits
                                 // #   6-4  | Clkgen Osc Trigger     | 1-bit
                                 // #   9-7  | Clkgen Downsampoler    | 7-bits
                                 // # 12-10  | Clkgen Clock Select    | 2-bits
                                 // #    13  | Prev Link IO Control   | 3-bits
                                 // #    14  | Prev Link CORE Control | 2-bits
                                 // #    15  | Prev CT CORE Control   | 2-bits
                                 // #    16  | Next Link IO Control   | 3-bits
                                 // #    17  | Next Link CORE Control | 2-bits
                                 // #    18  | Next CT CORE Control   | 2-bits
                                 // #    19  | Core Control           | 4-bits
                                 // #    20  | Host Control           | 4-bits
                                 // #    21  | Router Control         | 4-bits
                                 // #    22  | DMC Control            | 2-bits
                                 // #    23  | DMC trefi 0            | 8-bits
                                 // #    24  | DMC trefi 1            | 8-bits
                                 // #    25  | DMC tmrd trfc          | 8-bits
                                 // #    26  | DMC trc trp            | 8-bits
                                 // #    27  | DMC tras trrd          | 8-bits
                                 // #    28  | DMC trcd twr           | 8-bits
                                 // #    29  | DMC twtr trtp          | 8-bits
                                 // #    30  | DMC tcas               | 4-bits
                                 // #    31  | DMC col \ row width    | 8-bits
                                 // #    32  | DMC bank width         |
                                 // #        |     dqs_sel_cal        | 8-bits
                                 // #        |     init_cmd_cnt       |
                                 // #
                                 // #
                                 // # Number of masters = 2
                                 // # Number of clients = 32
                                 // # Max data width = 9
                                 // #
                                 // # Packet lengths
                                 // # <4b>___<2b>___<6b>_1b_<4b>___<9b>
                                 // # <4b>___<22b>
                                 // #
                                 // # There are 2 masters (ASIC and GW) but they are replicated systems. The lsb of
                                 // # the masterEn is the ASIC and the msb is the GW. The GW will be given WHID 0,0
                                 // # and the ASIC will be given WHID 1,0. Therefore, we want to keep the prev link
                                 // # of the GW in reset and the next link of the ASIC in reset.
                                 // #
                                 // ################################################################################
                                 // # Tag Trace Replay Packet Format
                                 // #
                                 // # M = number of masters
                                 // # N = max(1, clog2(#_of_tag_clients))
                                 // # D = max(client_1_width, client_2_width, ..., client_n_width)
                                 // # L = clog2(D+1)
                                 // #
                                 // # |<    4-bits    >|< M-bits >|< N-bits >|<     1-bit    >|< L-bits >|< D-bits >|
                                 // # +----------------+----------+----------+----------------+----------+----------+
                                 // # | replay command | masterEn |  nodeID  | data_not_reset |  length  |   data   |
                                 // # +----------------+----------+----------+----------------+----------+----------+
                                 // #
                                 // # Replay Commands
                                 // #   0 = 0000 = Wait a cycle
                                 // #   1 = 0001 = Send data
                                 // #   2 = 0010 = Receive data
                                 // #   3 = 0011 = Assert done_o ouput signal
                                 // #   4 = 0100 = End test (calls $finish)
                                 // #   5 = 0101 = Wait for cycle_counter == 0
                                 // #   6 = 0110 = Initialize cycle_counter with a 16 bit number
                                 // ################################################################################
                                 // #
                                 // # RESET BSG TAG MASTER
                                 // #
                                 // # First, we must reset the bsg_tag_master. To do this, we send a 1, then we
                                 // # send a bunch of 0's! By a bunch, the exact amount is (2^clog2(N+1+L+D))+1
                                 // # Send a full 0 packet to all masters
         0: data_o = width_p ' (26'b0001___11___000000_0_0000___000000000); // 0x0700000
                                 // # Wait ~32 cycles
         1: data_o = width_p ' (26'b0110___0000000000000000100000); // 0x1800020
         2: data_o = width_p ' (26'b0101___0000000000000000000000); // 0x1400000
                                 // ################################################################################
                                 // #  ___  ___   ___ _____ ___ _____ ___    _   ___    ___ _    _  _____ ___ _  _
                                 // # | _ )/ _ \ / _ \_   _/ __|_   _| _ \  /_\ | _ \  / __| |  | |/ / __| __| \| |
                                 // # | _ \ (_) | (_) || | \__ \ | | |   / / _ \|  _/ | (__| |__| ' < (_ | _|| .` |
                                 // # |___/\___/ \___/ |_| |___/ |_| |_|_\/_/ \_\_|    \___|____|_|\_\___|___|_|\_|
                                 // #
                                 // ################################################################################
                                 // ################################################################################
                                 // #
                                 // # RESET BSG TAG CLIENTS
                                 // #
                                 // # Next, we should reset each client node. To do this we send a packet
                                 // # that has all 1's for data, and has data_not_reset=0. The nodeID should
                                 // # be the ID of the client we are reseting, and length should be the
                                 // # corrent length of the packet. We should send this packet to each client.
                                 // #SEND  en   id=0   r l=1
         3: data_o = width_p ' (26'b0001___01___000000_0_0001___000000001); // 0x0500201
                                 // #SEND  en   id=1   r l=5
         4: data_o = width_p ' (26'b0001___01___000001_0_0101___000011111); // 0x0504A1F
                                 // #SEND  en   id=2   r l=5
         5: data_o = width_p ' (26'b0001___01___000010_0_0101___000011111); // 0x0508A1F
                                 // #SEND  en   id=3   r l=5
         6: data_o = width_p ' (26'b0001___01___000011_0_0101___000011111); // 0x050CA1F
                                 // #SEND  en   id=4   r l=1
         7: data_o = width_p ' (26'b0001___01___000100_0_0001___000000001); // 0x0510201
                                 // #SEND  en   id=5   r l=1
         8: data_o = width_p ' (26'b0001___01___000101_0_0001___000000001); // 0x0514201
                                 // #SEND  en   id=6   r l=1
         9: data_o = width_p ' (26'b0001___01___000110_0_0001___000000001); // 0x0518201
                                 // #SEND  en   id=7   r l=7
        10: data_o = width_p ' (26'b0001___01___000111_0_0111___001111111); // 0x051CE7F
                                 // #SEND  en   id=8   r l=7
        11: data_o = width_p ' (26'b0001___01___001000_0_0111___001111111); // 0x0520E7F
                                 // #SEND  en   id=9   r l=7
        12: data_o = width_p ' (26'b0001___01___001001_0_0111___001111111); // 0x0524E7F
                                 // #SEND  en   id=10  r l=2
        13: data_o = width_p ' (26'b0001___01___001010_0_0010___000000011); // 0x0528403
                                 // #SEND  en   id=11  r l=2
        14: data_o = width_p ' (26'b0001___01___001011_0_0010___000000011); // 0x052C403
                                 // #SEND  en   id=12  r l=2
        15: data_o = width_p ' (26'b0001___01___001100_0_0010___000000011); // 0x0530403
                                 // #SEND  en   id=22  r l=5
        16: data_o = width_p ' (26'b0001___01___010110_0_0101___000011111); // 0x0558A1F
                                 // #SEND  en   id=23  r l=1
        17: data_o = width_p ' (26'b0001___01___010111_0_0001___000000001); // 0x055C201
                                 // #SEND  en   id=24  r l=7
        18: data_o = width_p ' (26'b0001___01___011000_0_0111___001111111); // 0x0560E7F
                                 // #SEND  en   id=25  r l=2
        19: data_o = width_p ' (26'b0001___01___011001_0_0010___000000011); // 0x0564403
                                 // #SEND  en   id=26  r l=1
        20: data_o = width_p ' (26'b0001___01___011010_0_0001___000000001); // 0x0568201
                                 // #SEND  en   id=27  r l=5
        21: data_o = width_p ' (26'b0001___01___011011_0_0101___000011111); // 0x056CA1F
                                 // #SEND  en   id=28  r l=5
        22: data_o = width_p ' (26'b0001___01___011100_0_0101___000011111); // 0x0570A1F
                                 // #SEND  en   id=29  r l=5
        23: data_o = width_p ' (26'b0001___01___011101_0_0101___000011111); // 0x0574A1F
                                 // #SEND  en   id=30  r l=5
        24: data_o = width_p ' (26'b0001___01___011110_0_0101___000011111); // 0x0578A1F
                                 // #SEND  en   id=31  r l=1
        25: data_o = width_p ' (26'b0001___01___011111_0_0001___000000001); // 0x057C201
                                 // #SEND  en   id=32  r l=1
        26: data_o = width_p ' (26'b0001___01___100000_0_0001___000000001); // 0x0580201
                                 // #SEND  en   id=33  r l=1
        27: data_o = width_p ' (26'b0001___01___100001_0_0001___000000001); // 0x0584201
                                 // #SEND  en   id=34  r l=1
        28: data_o = width_p ' (26'b0001___01___100010_0_0001___000000001); // 0x0588201
                                 // #SEND  en   id=35  r l=3
        29: data_o = width_p ' (26'b0001___01___100011_0_0011___000000111); // 0x058C607
                                 // ################################################################################
                                 // #
                                 // # START CONFIGURATION
                                 // #
                                 // # The bsg tag network is now live! We can begin our configuration.
                                 // #   ### Set osc triggers low
                                 // #
                                 // #   #SEND  en   id=4   d l=1    {trigger}
                                 // #   0001___01___000100_1_0001___000000000
                                 // #   #SEND  en   id=5   d l=1    {trigger}
                                 // #   0001___01___000101_1_0001___000000000
                                 // #   #SEND  en   id=6   d l=1    {trigger}
                                 // #   0001___01___000110_1_0001___000000000
                                 // #   #SEND  en   id=35  d l=1    {trigger}
                                 // #   0001___01___100011_1_0001___000000000
                                 // #
                                 // #   ### Program the raw oscillators speed
                                 // #
                                 // #   #SEND  en   id=1   d l=5    {adt, cdt, fdt}
                                 // #   0001___01___000001_1_0101___000000000
                                 // #   #SEND  en   id=2   d l=5    {adt, cdt, fdt}
                                 // #   0001___01___000010_1_0101___000000000
                                 // #   #SEND  en   id=3   d l=5    {adt, cdt, fdt}
                                 // #   0001___01___000011_1_0101___000000000
                                 // #   #SEND  en   id=34  d l=5    {adt, cdt, fdt}
                                 // #   0001___01___100010_1_0101___000000000
                                 // #
                                 // #   ### Trigger oscillators
                                 // #
                                 // #   #SEND  en   id=4   d l=1    {trigger}
                                 // #   0001___01___000100_1_0001___000000001
                                 // #   0001___01___000100_1_0001___000000000
                                 // #   #SEND  en   id=5   d l=1    {trigger}
                                 // #   0001___01___000101_1_0001___000000001
                                 // #   0001___01___000101_1_0001___000000000
                                 // #   #SEND  en   id=6   d l=1    {trigger}
                                 // #   0001___01___000110_1_0001___000000001
                                 // #   0001___01___000110_1_0001___000000000
                                 // #   #SEND  en   id=35  d l=1    {trigger}
                                 // #   0001___01___100011_1_0001___000000001
                                 // #   0001___01___100011_1_0001___000000000
                                 // #
                                 // #   ### Async clk-gen reset to get things moving
                                 // #
                                 // #   #SEND  en   id=0   d l=1    {async_reset}
                                 // #   0001___01___000000_1_0001___000000000
                                 // #   0001___01___000000_1_0001___000000001
                                 // #   0001___01___000000_1_0001___000000000
                                 // #
                                 // #   ### Set downsamples and reset
                                 // #
                                 // #   #SEND  en   id=7   d l=7    {ds_val, reset}
                                 // #   0001___01___000111_1_0111___000000001
                                 // #   0001___01___000111_1_0111___000000000
                                 // #   #SEND  en   id=8   d l=7    {ds_val, reset}
                                 // #   0001___01___001000_1_0111___000000001
                                 // #   0001___01___001000_1_0111___000000000
                                 // #   #SEND  en   id=9   d l=7    {ds_val, reset}
                                 // #   0001___01___001001_1_0111___000000001
                                 // #   0001___01___001001_1_0111___000000000
                                 // #
                                 // #   ### Select the output clock (0=raw osc, 1=ds osc, 2=ext, 3=off)
                                 // #
                                 // #   #SEND  en   id=10  d l=2    {clk_select}
                                 // #   0001___01___001010_1_0010___000000001
                                 // #   #SEND  en   id=11  d l=2    {clk_select}
                                 // #   0001___01___001011_1_0010___000000001
                                 // #   #SEND  en   id=12  d l=2    {clk_select}
                                 // #   0001___01___001100_1_0010___000000001
                                 // ### Select the output clock (0=raw osc, 1=ds osc, 2=ext, 3=off)
                                 // #SEND  en   id=10  d l=2    {clk_select}
        30: data_o = width_p ' (26'b0001___01___001010_1_0010___000000010); // 0x052A402
                                 // #SEND  en   id=11  d l=2    {clk_select}
        31: data_o = width_p ' (26'b0001___01___001011_1_0010___000000010); // 0x052E402
                                 // #SEND  en   id=12  d l=2    {clk_select}
        32: data_o = width_p ' (26'b0001___01___001100_1_0010___000000010); // 0x0532402
                                 // #SEND  en   id=25  d l=2    {clk_select}
        33: data_o = width_p ' (26'b0001___01___011001_1_0010___000000010); // 0x0566402
                                 // ### Set delay line triggers low
                                 // #SEND  en   id=31  d l=1    {trigger}
        34: data_o = width_p ' (26'b0001___01___011111_1_0001___000000000); // 0x057E200
                                 // #SEND  en   id=32  d l=1    {trigger}
        35: data_o = width_p ' (26'b0001___01___100000_1_0001___000000000); // 0x0582200
                                 // #SEND  en   id=33  d l=1    {trigger}
        36: data_o = width_p ' (26'b0001___01___100001_1_0001___000000000); // 0x0586200
                                 // #SEND  en   id=34  d l=1    {trigger}
        37: data_o = width_p ' (26'b0001___01___100010_1_0001___000000000); // 0x058A200
                                 // ### Program the delay lines phase shift
                                 // #SEND  en   id=27  d l=5    {adt, cdt, fdt}
        38: data_o = width_p ' (26'b0001___01___011011_1_0101___000000000); // 0x056EA00
                                 // #SEND  en   id=28  d l=5    {adt, cdt, fdt}
        39: data_o = width_p ' (26'b0001___01___011100_1_0101___000000000); // 0x0572A00
                                 // #SEND  en   id=29  d l=5    {adt, cdt, fdt}
        40: data_o = width_p ' (26'b0001___01___011101_1_0101___000000000); // 0x0576A00
                                 // #SEND  en   id=30  d l=5    {adt, cdt, fdt}
        41: data_o = width_p ' (26'b0001___01___011110_1_0101___000000000); // 0x057AA00
                                 // ### Trigger delay lines
                                 // #SEND  en   id=31  d l=1    {trigger}
        42: data_o = width_p ' (26'b0001___01___011111_1_0001___000000001); // 0x057E201
        43: data_o = width_p ' (26'b0001___01___011111_1_0001___000000000); // 0x057E200
                                 // #SEND  en   id=32  d l=1    {trigger}
        44: data_o = width_p ' (26'b0001___01___100000_1_0001___000000001); // 0x0582201
        45: data_o = width_p ' (26'b0001___01___100000_1_0001___000000000); // 0x0582200
                                 // #SEND  en   id=33  d l=1    {trigger}
        46: data_o = width_p ' (26'b0001___01___100001_1_0001___000000001); // 0x0586201
        47: data_o = width_p ' (26'b0001___01___100001_1_0001___000000000); // 0x0586200
                                 // #SEND  en   id=34  d l=1    {trigger}
        48: data_o = width_p ' (26'b0001___01___100010_1_0001___000000001); // 0x058A201
        49: data_o = width_p ' (26'b0001___01___100010_1_0001___000000000); // 0x058A200
                                 // ### Async clk-gen reset to get things moving
                                 // #SEND  en   id=26  d l=1    {async_reset}
        50: data_o = width_p ' (26'b0001___01___011010_1_0001___000000000); // 0x056A200
        51: data_o = width_p ' (26'b0001___01___011010_1_0001___000000001); // 0x056A201
        52: data_o = width_p ' (26'b0001___01___011010_1_0001___000000000); // 0x056A200
                                 // ### Set downsamples and reset
                                 // #
                                 // #SEND  en   id=35  d l=2    {ds_val, reset}
        53: data_o = width_p ' (26'b0001___01___100011_1_0011___000000001); // 0x058E601
        54: data_o = width_p ' (26'b0001___01___100011_1_0011___000000000); // 0x058E600
                                 // ################################################################################
                                 // #  ___  ___   ___ _____ ___ _____ ___    _   ___   ___ ___     ___ ___  __  __ ___ _    _____  __
                                 // # | _ )/ _ \ / _ \_   _/ __|_   _| _ \  /_\ | _ \ |_ _/ _ \   / __/ _ \|  \/  | _ \ |  | __\ \/ /
                                 // # | _ \ (_) | (_) || | \__ \ | | |   / / _ \|  _/  | | (_) | | (_| (_) | |\/| |  _/ |__| _| >  <
                                 // # |___/\___/ \___/ |_| |___/ |_| |_|_\/_/ \_\_|   |___\___/   \___\___/|_|  |_|_| |____|___/_/\_\
                                 // #
                                 // ################################################################################
                                 // ################################################################################
                                 // #
                                 // # RESET BSG TAG CLIENTS
                                 // #
                                 // # Next, we should reset each client node. To do this we send a packet
                                 // # that has all 1's for data, and has data_not_reset=0. The nodeID should
                                 // # be the ID of the client we are reseting, and length should be the
                                 // # corrent length of the packet. We should send this packet to each client.
                                 // #SEND  en   id=13  r l=3
        55: data_o = width_p ' (26'b0001___11___001101_0_0011___000000111); // 0x0734607
                                 // #SEND  en   id=14  r l=2
        56: data_o = width_p ' (26'b0001___11___001110_0_0010___000000011); // 0x0738403
                                 // #SEND  en   id=15  r l=2
        57: data_o = width_p ' (26'b0001___11___001111_0_0010___000000011); // 0x073C403
                                 // #SEND  en   id=16  r l=3
        58: data_o = width_p ' (26'b0001___11___010000_0_0011___000000111); // 0x0740607
                                 // #SEND  en   id=17  r l=2
        59: data_o = width_p ' (26'b0001___11___010001_0_0010___000000011); // 0x0744403
                                 // #SEND  en   id=18  r l=2
        60: data_o = width_p ' (26'b0001___11___010010_0_0010___000000011); // 0x0748403
                                 // #SEND  en   id=19  r l=4
        61: data_o = width_p ' (26'b0001___11___010011_0_1001___000001111); // 0x074D20F
                                 // #SEND  en   id=20  r l=4
        62: data_o = width_p ' (26'b0001___11___010100_0_1001___000001111); // 0x075120F
                                 // #SEND  en   id=21  r l=4
        63: data_o = width_p ' (26'b0001___11___010101_0_1001___000001111); // 0x075520F
                                 // #SEND  en   id=36  r l=8
        64: data_o = width_p ' (26'b0001___11___100100_0_1000___011111111); // 0x07910FF
                                 // #SEND  en   id=37  r l=8
        65: data_o = width_p ' (26'b0001___11___100101_0_1000___011111111); // 0x07950FF
                                 // #SEND  en   id=38  r l=8
        66: data_o = width_p ' (26'b0001___11___100110_0_1000___011111111); // 0x07990FF
                                 // #SEND  en   id=39  r l=8
        67: data_o = width_p ' (26'b0001___11___100111_0_1000___011111111); // 0x079D0FF
                                 // #SEND  en   id=40  r l=8
        68: data_o = width_p ' (26'b0001___11___101000_0_1000___011111111); // 0x07A10FF
                                 // #SEND  en   id=41  r l=8
        69: data_o = width_p ' (26'b0001___11___101001_0_1000___011111111); // 0x07A50FF
                                 // #SEND  en   id=42  r l=8
        70: data_o = width_p ' (26'b0001___11___101010_0_1000___011111111); // 0x07A90FF
                                 // #SEND  en   id=43  r l=8
        71: data_o = width_p ' (26'b0001___11___101011_0_1000___011111111); // 0x07AD0FF
                                 // #SEND  en   id=44  r l=8
        72: data_o = width_p ' (26'b0001___11___101100_0_1000___011111111); // 0x07B10FF
                                 // #SEND  en   id=45  r l=8
        73: data_o = width_p ' (26'b0001___11___101101_0_1000___011111111); // 0x07B50FF
                                 // #SEND  en   id=46  r l=8
        74: data_o = width_p ' (26'b0001___11___101110_0_1000___011111111); // 0x07B90FF
                                 // #SEND  en   id=47  r l=8
        75: data_o = width_p ' (26'b0001___11___101111_0_1000___011111111); // 0x07BD0FF
                                 // #SEND  en   id=48  r l=8
        76: data_o = width_p ' (26'b0001___11___110000_0_1000___011111111); // 0x07C10FF
                                 // ################################################################################
                                 // #
                                 // # START CONFIGURATION
                                 // #
                                 // # The bsg tag network is now live! We can begin our configuration.
                                 // ### STEP 1: INITIALIZE EVERYTHING
                                 // # Reset both ASIC and GW Prev Link IO Control
                                 // #SEND  en   id=13  d l=3   {up_link_reset, down_link_reset, async_token_reset}
        77: data_o = width_p ' (26'b0001___11___001101_1_0011___000000110); // 0x0736606
                                 // # Reset both ASIC and GW Prev Link CORE Control
                                 // #SEND  en   id=14  d l=2   {up_link_reset, down_link_reset}
        78: data_o = width_p ' (26'b0001___11___001110_1_0010___000000011); // 0x073A403
                                 // # Reset both ASIC and GW Prev CT CORE Control
                                 // #SEND  en   id=15  d l=2   {reset, fifo_reset}
        79: data_o = width_p ' (26'b0001___11___001111_1_0010___000000011); // 0x073E403
                                 // # Reset both ASIC and GW Next Link IO Control
                                 // #SEND  en   id=16  d l=3   {up_link_reset, down_link_reset, async_token_reset}
        80: data_o = width_p ' (26'b0001___11___010000_1_0011___000000110); // 0x0742606
                                 // # Reset both ASIC and GW Next Link CORE Control
                                 // #SEND  en   id=17  d l=2   {up_link_reset, down_link_reset}
        81: data_o = width_p ' (26'b0001___11___010001_1_0010___000000011); // 0x0746403
                                 // # Reset both ASIC and GW Next CT CORE Control
                                 // #SEND  en   id=18  d l=2   {reset, fifo_reset}
        82: data_o = width_p ' (26'b0001___11___010010_1_0010___000000011); // 0x074A403
                                 // # Reset ASIC configs and set dids
                                 // #SEND  en   id=19  d l=9   {reset, did=1}
        83: data_o = width_p ' (26'b0001___01___010011_1_1001___100000001); // 0x054F301
                                 // #SEND  en   id=20  d l=9   {reset, did=0}
        84: data_o = width_p ' (26'b0001___01___010100_1_1001___100000000); // 0x0553300
                                 // #SEND  en   id=21  d l=9   {reset, did=1}
        85: data_o = width_p ' (26'b0001___01___010101_1_1001___100000001); // 0x0557301
                                 // # Reset GW configs and set dids
                                 // #SEND  en   id=19  d l=9   {reset, did=1}
        86: data_o = width_p ' (26'b0001___10___010011_1_1001___100000001); // 0x064F301
                                 // #SEND  en   id=20  d l=9   {reset, did=0}
        87: data_o = width_p ' (26'b0001___10___010100_1_1001___100000000); // 0x0653300
                                 // #SEND  en   id=21  d l=9   {reset, did=0}
        88: data_o = width_p ' (26'b0001___10___010101_1_1001___100000000); // 0x0657300
                                 // # Reset DMC configs and set dmc_p
                                 // #SEND  en   id=36  d l=8    {trefi[7:0]}
        89: data_o = width_p ' (26'b0001___01___100100_1_1000___011111111); // 0x05930FF
                                 // #SEND  en   id=37  d l=8    {trefi[15:8]}
        90: data_o = width_p ' (26'b0001___01___100101_1_1000___000000011); // 0x0597003
                                 // #SEND  en   id=38  d l=8    {trfc, tmrd}
        91: data_o = width_p ' (26'b0001___01___100110_1_1000___011110001); // 0x059B0F1
                                 // #SEND  en   id=39  d l=8    {trp, trc}
        92: data_o = width_p ' (26'b0001___01___100111_1_1000___000111010); // 0x059F03A
                                 // #SEND  en   id=40  d l=8    {trrd, tras}
        93: data_o = width_p ' (26'b0001___01___101000_1_1000___000010111); // 0x05A3017
                                 // #SEND  en   id=41  d l=8    {twr, trcd}
        94: data_o = width_p ' (26'b0001___01___101001_1_1000___010110010); // 0x05A70B2
                                 // #SEND  en   id=42  d l=8    {trtp, twtr}
        95: data_o = width_p ' (26'b0001___01___101010_1_1000___010000111); // 0x05AB087
                                 // #SEND  en   id=43  d l=8    {cas}
        96: data_o = width_p ' (26'b0001___01___101011_1_1000___000000011); // 0x05AF003
                                 // #SEND  en   id=44  d l=8    {row_width, col_width}
        97: data_o = width_p ' (26'b0001___01___101100_1_1000___011101011); // 0x05B30EB
                                 // #SEND  en   id=45  d l=8    {bank_pos, bank_width}
        98: data_o = width_p ' (26'b0001___01___101101_1_1000___001100110); // 0x05B7066
                                 // #SEND  en   id=46  d l=8    {init_cmd_cnt, dqs_sel_cal}
        99: data_o = width_p ' (26'b0001___01___101110_1_1000___000010100); // 0x05BB014
                                 // #SEND  en   id=47  d l=8    {reset}
                                 // #0001___01___101111_1_1000___000000000
       100: data_o = width_p ' (26'b0001___01___101111_1_1000___000000001); // 0x05BF001
       101: data_o = width_p ' (26'b0001___01___101111_1_1000___000000000); // 0x05BF000
                                 // # Setup ASIC bypass link switches
                                 // #SEND  en   id=48  d l=8    {SW2, SW1, SW0}
       102: data_o = width_p ' (26'b0001___01___110000_1_1000___000000001); // 0x05C3001
                                 // # Setup GW bypass link switches
                                 // #SEND  en   id=48  d l=8    {SW2, SW1, SW0}
       103: data_o = width_p ' (26'b0001___10___110000_1_1000___000000000); // 0x06C3000
                                 // ### STEP 2: Perform async token resets
                                 // # Async token reset for ASIC Prev IO Link
                                 // #SEND  en   id=13  d l=3   {up_link_reset, down_link_reset, async_token_reset}
       104: data_o = width_p ' (26'b0001___01___001101_1_0011___000000111); // 0x0536607
       105: data_o = width_p ' (26'b0001___01___001101_1_0011___000000110); // 0x0536606
                                 // # Assert async token reset for GW Next IO Link
                                 // #SEND  en   id=16  d l=3   {up_link_reset, down_link_reset, async_token_reset}
       106: data_o = width_p ' (26'b0001___10___010000_1_0011___000000111); // 0x0642607
       107: data_o = width_p ' (26'b0001___10___010000_1_0011___000000110); // 0x0642606
                                 // ### STEP 3: De-assert Upstream IO Links reset
                                 // # De-assert upstream reset for ASIC Prev IO Link
                                 // #SEND  en   id=13  d l=3   {up_link_reset, down_link_reset, async_token_reset}
       108: data_o = width_p ' (26'b0001___01___001101_1_0011___000000010); // 0x0536602
                                 // # De-assert upstream reset for GW Next IO Link
                                 // #SEND  en   id=16  d l=3   {up_link_reset, down_link_reset, async_token_reset}
       109: data_o = width_p ' (26'b0001___10___010000_1_0011___000000010); // 0x0642602
                                 // ### STEP 4: De-assert Downstream IO Links reset
                                 // # De-assert downstream reset for ASIC Prev IO Link
                                 // #SEND  en   id=13  d l=3   {up_link_reset, down_link_reset, async_token_reset}
       110: data_o = width_p ' (26'b0001___01___001101_1_0011___000000000); // 0x0536600
                                 // # De-assert downstream reset for GW Next IO Link
                                 // #SEND  en   id=16  d l=3   {up_link_reset, down_link_reset, async_token_reset}
       111: data_o = width_p ' (26'b0001___10___010000_1_0011___000000000); // 0x0642600
                                 // ### STEP 5/6: De-assert Upstream/Downstream CORE Links reset
                                 // # De-assert upstream/downstream reset for ASIC Prev CORE Link
                                 // #SEND  en   id=14  d l=2   {up_link_reset, down_link_reset}
       112: data_o = width_p ' (26'b0001___01___001110_1_0010___000000000); // 0x053A400
                                 // # De-assert upstream/downstream reset for GW Next CORE Link
                                 // #SEND  en   id=17  d l=2   {up_link_reset, down_link_reset}
       113: data_o = width_p ' (26'b0001___10___010001_1_0010___000000000); // 0x0646400
                                 // ### STEP 7: De-assert CT reset and fifo reset
                                 // # De-assert reset and fifo_reset for ASIC Prev CT CORE Control
                                 // #SEND  en   id=15  d l=2   {reset, fifo_reset}
       114: data_o = width_p ' (26'b0001___01___001111_1_0010___000000000); // 0x053E400
                                 // # De-assert reset and fifo_reset for GW Next CT CORE Control
                                 // #SEND  en   id=18  d l=2   {reset, fifo_reset}
       115: data_o = width_p ' (26'b0001___10___010010_1_0010___000000000); // 0x064A400
                                 // ### STEP 8: De-assert Router reset
                                 // # Deassert reset ASIC Routers and set did
                                 // #SEND  en   id=19  d l=9   {reset, did=1}
       116: data_o = width_p ' (26'b0001___01___010011_1_1001___000000001); // 0x054F201
                                 // #SEND  en   id=20  d l=9   {reset, did=0}
       117: data_o = width_p ' (26'b0001___01___010100_1_1001___000000000); // 0x0553200
                                 // #SEND  en   id=21  d l=9   {reset, did=1}
       118: data_o = width_p ' (26'b0001___01___010101_1_1001___000000001); // 0x0557201
                                 // # Deassert reset GW Routers and set did
                                 // #SEND  en   id=19  d l=9   {reset, did=1}
       119: data_o = width_p ' (26'b0001___10___010011_1_1001___000000001); // 0x064F201
                                 // #SEND  en   id=20  d l=9   {reset, did=0}
       120: data_o = width_p ' (26'b0001___10___010100_1_1001___000000000); // 0x0653200
                                 // #SEND  en   id=21  d l=9   {reset, did=0}
       121: data_o = width_p ' (26'b0001___10___010101_1_1001___000000000); // 0x0657200
                                 // ################################################################################
                                 // #
                                 // # Done!
                                 // #
                                 // # Configuration is complete and we are out of reset. We should indicate we are
                                 // # done to allow the next part of the testbench to come alive.
                                 // # Assert done_o
       122: data_o = width_p ' (26'b0011___0000000000000000000000); // 0x0C00000
   default: data_o = 'X;
endcase
endmodule
